"""Textos que ve la persona en el editor (static/editor/*.js), por clave. El
msgid es el español de siempre; `textos()` los devuelve en el idioma activo
(el de quien mira: la ruta `editor.ver` los mete en los datos de la página y
static/editor/textos.js los usa con `t()`). static/editor/textos.js trae el
MISMO diccionario en español (`ES`) para que los módulos puros y sus pruebas
de Node hablen igual sin página: tests/test_i18n_editor.py compara los dos.
Marcadores `{nombre}` (los reemplaza el JS), nunca `%(x)s`. Una clave se
escribe siempre entera en el módulo que la usa (nunca armada con `${…}`: la
prueba de claves no la vería). «Fuente» (la tipografía) es el único texto
con contexto: sin él saldría «Source», la fuente de datos de Nicho."""
from flask_babel import pgettext

import idiomas
from idiomas import N_

TEXTOS = {
    # pagina_editor.js / guardado.js: el estado del guardado
    "guardado.ok": N_("Guardado"),
    "guardado.pendiente": N_("Cambios sin guardar…"),
    "guardado.guardando": N_("Guardando…"),
    "guardado.error": N_("No se guardó: {mensaje}"),
    "guardado.conflicto": N_("La edición cambió en otra pestaña; recarga para seguir."),
    "guardado.fallo": N_("No se pudo guardar (error {status})."),
    "guardado.sin_conexion": N_("Sin conexión: se guarda con el próximo cambio."),
    # pagina_editor.js: editar
    "editar.conflicto": N_("Esta edición cambió en otra pestaña: recarga la página para seguir editando."),
    "editar.fallo": N_("No se pudo hacer ese cambio ({error}). La edición quedó como estaba."),
    "editar.cabezal_elegido": N_("Pon el cabezal sobre el clip elegido para cortarlo."),
    # pagina_editor.js: «Producir»
    "producir.sin_clon": N_("Esta edición no está unida a un video de Crear: todavía no se puede producir desde aquí."),
    "producir.un_minuto": N_("cerca de un minuto por destino"),
    "producir.minutos": N_("unos {n} minutos por destino"),
    "producir.reemplazo_una": N_("Ya hay una final de {destinos} hecha por otro camino (puede tener voz). Si produces, esta la reemplaza."),
    "producir.reemplazo_varias": N_("Ya hay finales de {destinos} hechas por otro camino (pueden tener voz). Si produces, estas las reemplazan."),
    "producir.marca_destino": N_("Marca al menos un destino."),
    "producir.guardar_antes": N_("Primero hay que guardar: {mensaje}"),
    "producir.error": N_("No se pudo producir (error {status})."),
    "producir.hecha_una": N_("Produciendo {n} final. Las vas a ver en Final edition cuando terminen."),
    "producir.hechas": N_("Produciendo {n} finales. Las vas a ver en Final edition cuando terminen."),
    "producir.ya_estaban": N_("Esos destinos ya se estaban produciendo."),
    "producir.sin_conexion": N_("Sin conexión: no se pudo producir. Vuelve a intentar."),
    # operaciones.js: OperacionInvalida (los mensajes de contrato quedan en español: INTERNOS)
    "op.sin_principal": N_("Esta edición no tiene una pista de video principal."),
    "op.no_existe": N_("Ese clip ya no existe en la edición."),
    "op.sonido_sigue": N_("El sonido de la escena sigue a los clips de video: edita el clip de video."),
    "op.demasiadas_pistas": N_("Esta edición ya tiene demasiadas pistas."),
    "op.cabezal_fuera": N_("Pon el cabezal dentro de un clip para cortarlo."),
    "op.muy_cerca": N_("Muy cerca del borde del clip para cortar ahí."),
    "op.muy_cerca_clip": N_("Muy cerca del borde del clip para cortarlo."),
    "op.un_clip": N_("La edición necesita al menos un clip de video."),
    "op.voz_destino": N_("La voz se ajusta sola a cada país: puedes moverla o borrarla, pero no recortarla."),
    "op.fuera_principal": N_("Ese clip no está en la pista principal."),
    "op.reordenar": N_("Los clips de la pista principal se reordenan, no se mueven a un tiempo suelto."),
    "op.velocidad_video": N_("La velocidad solo se cambia en clips de video."),
    "op.velocidad_no": N_("Esa velocidad no está disponible ({v}×)."),
    "op.muy_corto": N_("El clip quedaría demasiado corto a esa velocidad."),
    "op.video_preparando": N_("Ese video todavía se está preparando."),
    "op.audio_preparando": N_("Ese audio todavía se está preparando."),
    "op.texto_nuevo": N_("Escribe aquí"),
    "op.transicion_principal": N_("Esa transición solo se pone en un clip de la pista principal."),
    "op.transicion_ultimo": N_("El último clip no tiene transición hacia el siguiente."),
    "op.no_es_texto": N_("Eso no es un clip de texto."),
    "op.texto_vacio": N_("El texto no puede quedar vacío."),
    "op.sin_cambios": N_("No hay cambios que aplicar."),
    "op.estilo_solo_texto": N_("El estilo solo se cambia en clips de texto."),
    "op.audio_sin_posicion": N_("Un clip de audio no tiene posición ni tamaño."),
    "op.audio_solo_audio": N_("El audio solo se cambia en clips de audio."),
    "op.sonido_no_cabe": N_("Esta edición ya tiene demasiadas pistas: no cabe el sonido del video."),
    "op.sin_sonido_escena": N_("Ese clip no tiene sonido de la escena todavía."),
    # vista.js
    "vista.nombre_imagen": N_("la imagen"),
    "vista.nombre_video": N_("el video"),
    "vista.nombre_archivo": N_("el archivo"),
    "vista.nombre_con_archivo": N_("{tipo} «{archivo}»"),
    "vista.carga_una": N_("No se pudo cargar {lista} (el enlace no respondió o el archivo ya no está): esa parte queda vacía en la vista previa."),
    "vista.carga_varias": N_("No se pudieron cargar {lista} (el enlace no respondió o el archivo ya no está): esas partes quedan vacías en la vista previa."),
    "vista.sonido_fallo": N_("No se pudo cargar el sonido de {n} archivo(s) (puede ser la conexión o que el almacenamiento no dé permiso de lectura): la vista previa sigue sin ese sonido."),
    "vista.destino_sin_valor": N_("{mensaje} Elige otro destino."),
    "vista.destino_error": N_("No se pudo preparar este destino: {mensaje}"),
    "vista.cargando_sonido": N_("Cargando el sonido…"),
    "vista.sin_sonido": N_("La vista previa va sin sonido: {mensaje}"),
    "vista.pausar": N_("Pausar"),
    "vista.reproducir": N_("Reproducir"),
    "vista.dibujo": N_("La vista previa tuvo un problema al dibujar ({mensaje}). Recarga la página; si se repite, avísanos."),
    "vista.proxies_uno": N_("No se pudo preparar las copias livianas de {n} archivo(s): la vista previa sigue con los originales (se ve igual, solo tarda más en cargar)."),
    "vista.proxies_varios": N_("No se pudieron preparar las copias livianas de {n} archivo(s): la vista previa sigue con los originales (se ve igual, solo tarda más en cargar)."),
    "vista.preparando": N_("Preparando {n} archivo(s) para que la vista previa sea más liviana. Es gratis; mientras tanto se usan los originales."),
    "vista.no_producible": N_("Esta edición no se puede producir tal como está: {aviso}"),
    "vista.faltan": N_("Faltan {n} archivo(s) de esta edición (se borraron o no son de este proyecto): esas partes no se verán."),
    # resolver.js
    "resolver.sin_valor": N_("El texto '{rol}' no tiene valor en {idioma}."),
    # precio.js / resolver.js
    "precio.sin_formato": N_("No sé formatear precios de {pais}."),
    # escala.js (filas y cabeceras), propiedades*.js
    "fila.voz": N_("Voz"),
    "fila.musica": N_("Música"),
    "fila.sonido": N_("Sonido"),
    "fila.efecto": N_("Efecto"),
    "fila.audio": N_("Audio"),
    "fila.grabacion": N_("Grabación"),
    "fila.texto": N_("Texto"),
    "fila.textos": N_("Textos"),
    "fila.imagenes": N_("Imágenes"),
    "fila.superpuesto": N_("Video encima"),
    "fila.video": N_("Video"),
    "fila.sonido_escena": N_("Sonido de la escena"),
    "fila.pista": N_("Pista"),
    # escala.js (clips), biblioteca.js, propiedades*.js
    "clip.precio": N_("Precio"),
    "clip.texto": N_("Texto «{rol}»"),
    "clip.imagen": N_("Imagen"),
    # escala.js: transiciones
    "tr.corte": N_("Corte"),
    "tr.fundido": N_("Fundido"),
    "tr.deslizar": N_("Deslizar"),
    "tr.zoom": N_("Zoom"),
    "tr.desenfoque": N_("Fundido a negro"),
    "tr.union_corte": N_("Esa unión quedó en corte: el primer clip no tiene video de sobra al final para la transición. Recorta un poco su final y vuelve a ponerla."),
    "tr.acortada": N_("La transición quedó de {duracion}: no hay más video al final del primer clip."),
    # linea_tiempo.js
    "tl.transicion": N_("Transición: {nombre}"),
    # biblioteca.js
    "bib.tipo_no": N_("Sube un video, una imagen o un audio."),
    "bib.pesa_video": N_("El video pesa más de {mb} MB."),
    "bib.pesa_imagen": N_("La imagen pesa más de {mb} MB."),
    "bib.pesa_audio": N_("El audio pesa más de {mb} MB."),
    "bib.sin_conexion_subir": N_("Sin conexión: no se pudo subir. Vuelve a intentar."),
    "bib.sesion_subir": N_("Tu sesión venció: vuelve a entrar y súbelo otra vez."),
    "bib.muy_grande": N_("El archivo es demasiado grande."),
    "bib.servidor": N_("El servidor no pudo guardar el archivo. Vuelve a intentar."),
    "bib.error_subir": N_("No se pudo subir (error {status})."),
    "bib.texto_titulo": N_("Título"),
    "bib.texto_subtitulo": N_("Subtítulo"),
    "bib.texto_llamado": N_("Llamado"),
    "bib.tr_corte": N_("Sin transición: pasa de golpe."),
    "bib.tr_fundido": N_("Un video se funde en el otro."),
    "bib.tr_deslizar": N_("El siguiente entra desde la derecha."),
    "bib.tr_zoom": N_("Se acerca y pasa al siguiente."),
    "bib.tr_desenfoque": N_("Baja a negro y aparece el siguiente."),
    "bib.en_espera": N_("En espera"),
    "bib.subiendo": N_("Subiendo {n} %"),
    "bib.listo": N_("Listo"),
    "bib.no_subio": N_("No se subió"),
    "bib.logo": N_("Logo"),
    "bib.cancion": N_("Canción"),
    "bib.video_crear": N_("Video de Crear"),
    "bib.subir": N_("Subir"),
    "bib.arrastra": N_("o arrastra archivos aquí"),
    "bib.tus_archivos": N_("Tus archivos"),
    "bib.videos_crear": N_("Videos de Crear"),
    "bib.subir_audio": N_("Subir audio"),
    "bib.audios": N_("Audios del proyecto"),
    "bib.ayuda_textos": N_("Toca uno para ponerlo donde está el cabezal; con el mouse también puedes arrastrarlo a la línea de tiempo."),
    "bib.agregar_texto": N_("Agregar un texto «{nombre}»"),
    "bib.ayuda_transiciones": N_("Toca una para ponerla en el video que elegiste o, si no, en el corte más cercano al cabezal. Dura medio segundo; con el mouse también puedes arrastrarla a un corte."),
    "bib.transicion": N_("Transición «{nombre}»: {descripcion}"),
    "bib.cargando": N_("Cargando…"),
    "bib.vacio_medios": N_("Todavía no hay videos ni imágenes en este proyecto. Súbelos con «Subir» (o arrástralos aquí desde tu computadora)."),
    "bib.vacio_piezas": N_("Cuando un video de Crear esté listo, aparece aquí."),
    "bib.vacio_audios": N_("Todavía no hay audios. Sube uno aquí, o crea canciones en Crear › Mi música."),
    "bib.error_carga": N_("No se pudo cargar la biblioteca."),
    "bib.reintentar": N_("Reintentar"),
    "bib.agregar": N_("Agregar a la edición"),
    "bib.agregar_nombre": N_("Agregar «{nombre}» a la edición"),
    "bib.preparando": N_("Preparando…"),
    "bib.se_prepara": N_("«{nombre}» se está preparando"),
    "bib.mi_musica": N_("Mi música"),
    "bib.subido": N_("Subido"),
    "bib.agregar_musica": N_("Agregar «{nombre}» como música desde el cabezal"),
    "bib.sin_videos": N_("Una transición va entre dos videos: agrega otro video primero."),
    "bib.no_agregado": N_("No se pudo agregar: el aviso está debajo del video."),
    "bib.union_corte": N_("Esa unión quedó en corte, sin transición."),
    "bib.en_union": N_("«{nombre}» quedó en la unión."),
    "bib.texto_agregado": N_("Texto agregado: escríbelo en «Editar»."),
    "bib.agregado": N_("Se agregó «{nombre}»."),
    "bib.se_agrega_sola": N_("«{nombre}» se está preparando: se agrega sola cuando esté."),
    "bib.preparando_pieza": N_("Preparando «{nombre}» para el editor (gratis): se agrega sola cuando esté."),
    "bib.sin_conexion_pieza": N_("Sin conexión: no se pudo preparar ese video. Vuelve a intentar."),
    "bib.sesion": N_("Tu sesión venció: vuelve a entrar para seguir."),
    "bib.error_pieza": N_("No se pudo preparar ese video (error {status})."),
    "bib.ese_video": N_("ese video"),
    "bib.no_preparo": N_("No se pudo preparar «{nombre}». Vuelve a intentar."),
    "bib.tarda": N_("«{nombre}» tarda demasiado en prepararse. Vuelve a intentar en un rato."),
    "bib.quitar": N_("Quitar"),
    "bib.quitar_nombre": N_("Quitar «{nombre}» de la lista"),
    "bib.subida_de": N_("Subida de «{nombre}»"),
    "bib.parar": N_("Parar"),
    "bib.escuchar": N_("Escuchar"),
    "bib.parar_nombre": N_("Parar «{nombre}»"),
    "bib.escuchar_nombre": N_("Escuchar «{nombre}»"),
    "bib.no_escucha": N_("No se pudo escuchar ese audio."),
    # propiedades_modelo.js y propiedades.js
    "prop.ayuda_vacia": N_("Elige algo en la línea de tiempo o en el video para cambiarlo."),
    "prop.mezcla_equilibrada": N_("Equilibrada"),
    "prop.mezcla_voz": N_("Voz primero"),
    "prop.mezcla_ambiente": N_("Ambiente primero"),
    "prop.ayuda_equilibrada": N_("Voz, sonido del video y música, cada uno en su punto."),
    "prop.ayuda_voz": N_("El sonido del video y la música bajan para que la voz se entienda."),
    "prop.ayuda_ambiente": N_("El sonido del video se oye entero y la música queda baja."),
    "prop.fuente_inter_gruesa": N_("Inter gruesa"),
    "prop.fuente_inter_media": N_("Inter media"),
    "prop.fuente_space": N_("Space Grotesk"),
    "prop.color_blanco": N_("Blanco"),
    "prop.color_negro": N_("Negro"),
    "prop.color_amarillo": N_("Amarillo"),
    "prop.color_rojo": N_("Rojo"),
    "prop.color_marca": N_("Color de marca"),
    "prop.porcentaje": N_("{n} %"),
    "prop.clip": N_("Clip"),
    "prop.sin_sonido": N_("Sin sonido: súbelo para oír el sonido de este video."),
    "prop.velocidad_sin_sonido": N_("A otra velocidad el video va sin su sonido."),
    "prop.video_sin_sonido": N_("Este video no trae sonido."),
    "prop.ultimo_video": N_("Es el último video: no tiene transición hacia el siguiente."),
    "prop.nota_precio": N_("Es el precio de cada país: sale de los precios de la edición y no se escribe aquí."),
    "prop.nota_por_pais": N_("Este texto cambia según el país: lo que escribas aquí vale para {destino}."),
    "prop.nota_voz": N_("La voz se ajusta sola a cada país."),
    "prop.conflicto": N_("La edición cambió en otra pestaña: recarga la página para seguir."),
    "prop.rechazo": N_("No se pudo hacer ese cambio: el aviso está debajo del video."),
    "prop.ninguno": N_("Ninguno"),
    "prop.acercar": N_("Acercar"),
    "prop.alejar": N_("Alejar"),
    "prop.pildora": N_("Píldora"),
    "prop.caja": N_("Caja"),
    "prop.izquierda": N_("Izquierda"),
    "prop.centro": N_("Centro"),
    "prop.derecha": N_("Derecha"),
    "prop.ninguna": N_("Ninguna"),
    "prop.anim_deslizar": N_("Deslizar"),
    "prop.texto_vacio": N_("Escribe algo: un texto no puede quedar vacío."),
    "prop.borrar": N_("Borrar"),
    "prop.toda": N_("Toda la edición"),
    "prop.mezcla": N_("Mezcla del sonido"),
    "prop.a_medida": N_("Esta edición trae volúmenes a medida: elegir una mezcla los reemplaza."),
    "prop.velocidad": N_("Velocidad"),
    "prop.volumen_sonido": N_("Volumen del sonido"),
    "prop.zoom_lento": N_("Zoom lento"),
    "prop.transicion_siguiente": N_("Transición al siguiente"),
    "prop.tipo": N_("Tipo"),
    "prop.duracion": N_("Duración"),
    "prop.fuente": "Fuente",       # sin N_: se traduce con contexto en textos() (pgettext "editor")
    "prop.tamano": N_("Tamaño"),
    "prop.contorno": N_("Contorno"),
    "prop.color_contorno": N_("Color del contorno"),
    "prop.grosor": N_("Grosor"),
    "prop.sombra": N_("Sombra"),
    "prop.fondo": N_("Fondo"),
    "prop.color_fondo": N_("Color del fondo"),
    "prop.opacidad_fondo": N_("Opacidad del fondo"),
    "prop.alineacion": N_("Alineación"),
    "prop.animacion": N_("Animación de entrada"),
    "prop.posicion": N_("Posición"),
    "prop.centrar_ancho": N_("Centrar a lo ancho"),
    "prop.centrado_ancho": N_("Ya está centrado a lo ancho."),
    "prop.centrar_alto": N_("Centrar a lo alto"),
    "prop.centrado_alto": N_("Ya está centrado a lo alto."),
    "prop.color": N_("Color"),
    "prop.otro": N_("Otro"),
    "prop.tamano_imagen": N_("Tamaño (del ancho de la pantalla)"),
    "prop.opacidad": N_("Opacidad"),
    "prop.llenar": N_("Llenar la pantalla"),
    "prop.imagen_chica": N_("La imagen es chica: quedó lo más grande posible, pero no llega a llenar toda la pantalla."),
    "prop.centrar": N_("Centrar"),
    "prop.volumen": N_("Volumen"),
    "prop.fundido_entrada": N_("Fundido de entrada"),
    "prop.fundido_salida": N_("Fundido de salida"),
    "prop.silenciar": N_("Silenciar"),
    "prop.volver_oir": N_("Volver a oír"),
    "prop.nota_sonido": N_("Es el sonido del video: su volumen se cambia desde el clip de video."),
    "prop.elegir_video": N_("Elegir el video"),
    "prop.nota_otro": N_("El video final no muestra este clip: aquí solo se puede borrar."),
}


def textos():
    """TEXTOS en el idioma activo (en una ruta: el de quien mira)."""
    salida = {clave: idiomas.traducir(msgid) for clave, msgid in TEXTOS.items()}
    salida["prop.fuente"] = pgettext("editor", "Fuente")     # msgctxt "editor" → «Font»
    return salida
