"""tablas motor

Revision ID: 0001
Revises: 
Create Date: 2026-09-14 16:09:30.394126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kv',
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('fuente_id', sa.String(length=120), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('url_compra', sa.Text(), nullable=True),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('activo_catalogo_id', sa.String(length=120), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('en_prueba', sa.Boolean(), nullable=True),
    sa.Column('archivado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente', 'fuente', 'fuente_id', name='uq_producto_fuente')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_cliente'), ['cliente'], unique=False)

    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=True),
    sa.Column('job_id', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('max_intentos', sa.Integer(), nullable=True),
    sa.Column('ejecutar_desde', sa.String(length=19), nullable=False),
    sa.Column('creada_en', sa.String(length=19), nullable=False),
    sa.Column('iniciada_en', sa.String(length=19), nullable=True),
    sa.Column('terminada_en', sa.String(length=19), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duracion_estimada', sa.Float(), nullable=True),
    sa.Column('etapas', sa.JSON(), nullable=True),
    sa.Column('etapa_actual', sa.String(length=120), nullable=True),
    sa.Column('indice_etapa', sa.Integer(), nullable=True),
    sa.Column('inicio_etapa', sa.Float(), nullable=True),
    sa.Column('inicio', sa.Float(), nullable=True),
    sa.Column('progreso_etapa', sa.Float(), nullable=True),
    sa.Column('progreso_visto', sa.Float(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarea_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarea_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarea_job_id'), ['job_id'], unique=False)

    op.create_table('tienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('credenciales', sa.Text(), nullable=True),
    sa.Column('ultima_sync_productos', sa.String(length=19), nullable=True),
    sa.Column('ultima_sync_pedidos', sa.String(length=19), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tienda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tienda_cliente'), ['cliente'], unique=False)

    op.create_table('concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('referencia_url', sa.Text(), nullable=True),
    sa.Column('referencia_frames', sa.JSON(), nullable=True),
    sa.Column('referencia_transcripcion', sa.Text(), nullable=True),
    sa.Column('enfoque', sa.String(length=20), nullable=True),
    sa.Column('guion_base', sa.JSON(), nullable=True),
    sa.Column('idioma_base', sa.String(length=5), nullable=True),
    sa.Column('padre_concepto_id', sa.Integer(), nullable=True),
    sa.Column('motivo_archivo', sa.Text(), nullable=True),
    sa.Column('archivado', sa.Boolean(), nullable=True),
    sa.Column('legado_id', sa.String(length=60), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['padre_concepto_id'], ['concepto.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepto_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepto_legado_id'), ['legado_id'], unique=False)

    op.create_table('experimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('modo', sa.String(length=8), nullable=False),
    sa.Column('reglas', sa.JSON(), nullable=True),
    sa.Column('paises', sa.JSON(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('tope_total', sa.Float(), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('objetivo_meta', sa.String(length=30), nullable=True),
    sa.Column('atribucion', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=22), nullable=False),
    sa.Column('meta_campaign_id', sa.String(length=40), nullable=True),
    sa.Column('gasto_acumulado', sa.Float(), nullable=True),
    sa.Column('legado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experimento_cliente'), ['cliente'], unique=False)

    op.create_table('pieza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('modelo', sa.String(length=40), nullable=True),
    sa.Column('url_video', sa.Text(), nullable=True),
    sa.Column('url_miniatura', sa.Text(), nullable=True),
    sa.Column('url_local', sa.Text(), nullable=True),
    sa.Column('duracion_s', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=6), nullable=True),
    sa.Column('capas', sa.JSON(), nullable=True),
    sa.Column('costo_usd', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('padre_pieza_id', sa.Integer(), nullable=True),
    sa.Column('guion', sa.JSON(), nullable=True),
    sa.Column('legado_id', sa.String(length=60), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto.id'], ),
    sa.ForeignKeyConstraint(['padre_pieza_id'], ['pieza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pieza', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pieza_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_pieza_concepto_id'), ['concepto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pieza_legado_id'), ['legado_id'], unique=False)

    op.create_table('propuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('experimento_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=12), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('resuelta_en', sa.String(length=19), nullable=True),
    sa.ForeignKeyConstraint(['experimento_id'], ['experimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propuesta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propuesta_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_propuesta_experimento_id'), ['experimento_id'], unique=False)

    op.create_table('experimento_pieza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('experimento_id', sa.Integer(), nullable=False),
    sa.Column('pieza_id', sa.Integer(), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('meta_adset_id', sa.String(length=40), nullable=True),
    sa.Column('meta_ad_id', sa.String(length=40), nullable=True),
    sa.Column('meta_creative_id', sa.String(length=40), nullable=True),
    sa.Column('estado_meta', sa.String(length=30), nullable=True),
    sa.Column('veredicto', sa.String(length=12), nullable=True),
    sa.Column('veredicto_motivo', sa.Text(), nullable=True),
    sa.Column('veredicto_en', sa.String(length=19), nullable=True),
    sa.Column('escalon_rescate', sa.Integer(), nullable=True),
    sa.Column('presupuesto_dia_actual', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('legado_id', sa.String(length=60), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experimento_id'], ['experimento.id'], ),
    sa.ForeignKeyConstraint(['pieza_id'], ['pieza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experimento_pieza', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experimento_pieza_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimento_pieza_experimento_id'), ['experimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experimento_pieza_legado_id'), ['legado_id'], unique=False)

    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('experimento_id', sa.Integer(), nullable=True),
    sa.Column('experimento_pieza_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.ForeignKeyConstraint(['experimento_id'], ['experimento.id'], ),
    sa.ForeignKeyConstraint(['experimento_pieza_id'], ['experimento_pieza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_experimento_id'), ['experimento_id'], unique=False)

    op.create_table('metrica_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experimento_pieza_id', sa.Integer(), nullable=False),
    sa.Column('tomado_en', sa.String(length=19), nullable=False),
    sa.Column('impresiones', sa.Integer(), nullable=True),
    sa.Column('alcance', sa.Integer(), nullable=True),
    sa.Column('frecuencia', sa.Float(), nullable=True),
    sa.Column('clics', sa.Integer(), nullable=True),
    sa.Column('clics_enlace', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('thruplay', sa.Integer(), nullable=True),
    sa.Column('thruplay_rate', sa.Float(), nullable=True),
    sa.Column('gasto', sa.Float(), nullable=True),
    sa.Column('compras', sa.Integer(), nullable=True),
    sa.Column('ingresos', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('cpa', sa.Float(), nullable=True),
    sa.Column('fuente_ventas', sa.String(length=8), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experimento_pieza_id'], ['experimento_pieza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrica_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrica_snapshot_experimento_pieza_id'), ['experimento_pieza_id'], unique=False)

    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('fuente_id', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=19), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('utm_content', sa.String(length=120), nullable=True),
    sa.Column('experimento_pieza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experimento_pieza_id'], ['experimento_pieza.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente', 'fuente_id', name='uq_pedido_fuente')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_cliente'), ['cliente'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_cliente'))

    op.drop_table('pedido')
    with op.batch_alter_table('metrica_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrica_snapshot_experimento_pieza_id'))

    op.drop_table('metrica_snapshot')
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_experimento_id'))
        batch_op.drop_index(batch_op.f('ix_evento_cliente'))

    op.drop_table('evento')
    with op.batch_alter_table('experimento_pieza', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experimento_pieza_legado_id'))
        batch_op.drop_index(batch_op.f('ix_experimento_pieza_experimento_id'))
        batch_op.drop_index(batch_op.f('ix_experimento_pieza_cliente'))

    op.drop_table('experimento_pieza')
    with op.batch_alter_table('propuesta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_propuesta_experimento_id'))
        batch_op.drop_index(batch_op.f('ix_propuesta_cliente'))

    op.drop_table('propuesta')
    with op.batch_alter_table('pieza', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pieza_legado_id'))
        batch_op.drop_index(batch_op.f('ix_pieza_concepto_id'))
        batch_op.drop_index(batch_op.f('ix_pieza_cliente'))

    op.drop_table('pieza')
    with op.batch_alter_table('experimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experimento_cliente'))

    op.drop_table('experimento')
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepto_legado_id'))
        batch_op.drop_index(batch_op.f('ix_concepto_cliente'))

    op.drop_table('concepto')
    with op.batch_alter_table('tienda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tienda_cliente'))

    op.drop_table('tienda')
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarea_job_id'))
        batch_op.drop_index(batch_op.f('ix_tarea_estado'))
        batch_op.drop_index(batch_op.f('ix_tarea_cliente'))

    op.drop_table('tarea')
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_cliente'))

    op.drop_table('producto')
    op.drop_table('kv')
    # ### end Alembic commands ###
