"""Triple Whale tabla para conexiones y atribución.

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-22 02:28:10.199983
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triple_whale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.String(length=19), nullable=False),
    sa.Column('actualizado_en', sa.String(length=19), nullable=False),
    sa.Column('llave', sa.Text(), nullable=True),
    sa.Column('dominio_tienda', sa.String(length=200), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('modelo_atribucion', sa.String(length=50), nullable=True),
    sa.Column('ventana_atribucion', sa.String(length=30), nullable=True),
    sa.Column('zona_horaria', sa.String(length=50), nullable=True),
    sa.Column('ultima_sincronizacion', sa.String(length=19), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triple_whale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triple_whale_cliente'), ['cliente'], unique=False)

    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatar_estudio'))
        batch_op.create_index(batch_op.f('ix_avatar_estudio_id'), ['estudio_id'], unique=False)

    # Nota: funnel se agregó en 0014 y debe permanecer en 0015

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentario_estudio'))
        batch_op.create_index(batch_op.f('ix_comentario_estudio_id'), ['estudio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentario_estudio_id'))
        batch_op.create_index(batch_op.f('ix_comentario_estudio'), ['estudio_id'], unique=False)

    # Nota: funnel permanece de la migración 0014

    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatar_estudio_id'))
        batch_op.create_index(batch_op.f('ix_avatar_estudio'), ['estudio_id'], unique=False)

    with op.batch_alter_table('triple_whale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triple_whale_cliente'))

    op.drop_table('triple_whale')
    # ### end Alembic commands ###
